### PR TITLE
Add throttle support

### PR DESCRIPTION
**Pull request by NROL39**

### CODE REVIEW

**Comment by dr-dimitru** [comment]
@NROL39 why? I mean what this PR actually fixes/enhances

**Comment by NROL39** [comment]
It adds throttling support, let's say you have a hundred users, your server has 100mbps bandwidth, at the moment what will happen is that you'll be sending data as fast as possible, choking the other connections (try downloading multiple large files at the same time, you'll notice some will be downloading at a fast rate while some will have much lower rate).

Basically, it's so you can divide resources between multiple clients without having clients interfere with each other's downloads

**Comment by dr-dimitru** [comment]
@NROL39 got it, but why not make build in (all pipes by default) with ability to change (bps). Now if user does not passes `throttle` to Files instance, this feature won't be used

**Comment by NROL39** [comment]
That's right, I feel this should be an opt-in feature rather than an opt-out (although this is entirely up to you)

**Comment by dr-dimitru** [comment]
Better to have it enabled by default. But we need to specify default bps? Which value will be optimal?

**Comment by NROL39** [comment]
Well, it depends on the server's bandwidth, average file size and concurrent user count, every project will have it's own optimal range which is why i think it should be opt-in.

**Comment by dr-dimitru** [comment]
Agree now.
And why this feature is not applied to `206` responce

**Comment by NROL39** [comment]
There we go, 206 support added.

**Comment by dr-dimitru** [comment]
@NROL39 Thank you. I'll run tests, then merge and publish

**Comment by dr-dimitru** [comment]
Could you also add `check @throttle, Match.oneOf Boolean, Number` into `constructor` and update docs and in-code doc-block?

**Pull request merged**
