### PR TITLE
Allow to pass _preCollection options

### PR DESCRIPTION
**Pull request by Gariest**
#585

### CODE REVIEW

**Comment by dr-dimitru** [comment]
@Gariest please leave a comment and mention me after you will push requested changes.
So I won't miss it, and merge your awesome PR  😉

**Comment by Gariest** [comment]
@dr-dimitru Done. Sorry for letting you waiting. Cheers.

**Comment by dr-dimitru** [comment]
LGTM!
Thank you @Gariest

**Comment by dr-dimitru** [comment]
@Gariest thank you for contribution, published as [`v1.9.9`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.9.9).

Let me know how it works on your end.

**Pull request merged**
