### PR TITLE
fix wrong variable name in example

### PR DESCRIPTION
**Pull request by noris666**
1. Make sure you're sending PR to `dev` branch
 2. Give a short description what you have changed/added and why

### CODE REVIEW

**Comment by dr-dimitru** [comment]
See №1 from your message, please

**Comment by noris666** [comment]
@dr-dimitru done.

**Comment by dr-dimitru** [comment]
@noris666 looks like this variable has long and complicated history: https://github.com/VeliovGroup/Meteor-Files/wiki/Create-and-Manage-Subversions/_history# XD

**Comment by noris666** [comment]
:-D

**Comment by dr-dimitru** [comment]
@noris666 thank you for contribution and your accuracy 👌

**Pull request merged**
