### PR TITLE
Add react example and conversion from CFS package

### PR DESCRIPTION
**Pull request by vtocco**
React plus a document that shows how you can move files from the now depreciated CollectionFS/CFS packages to this one (amazon S3 specifically).

### CODE REVIEW

**Comment by vtocco** [comment]
Missed toc

**Comment by dr-dimitru** [comment]
Could you please send same PR to `dev` branch?

**Comment by vtocco** [comment]
Sure

**Comment by vtocco** [comment]
Looks like there are other commits, can you do a PR for those or want me to include them?

**Comment by dr-dimitru** [comment]
What commits?

**Comment by dr-dimitru** [comment]
just 
```shell
git checkout dev
git pull
git commit
git push
```

**Comment by vtocco** [comment]
Yeah, I have my own fork, and updated it, when I try to do a PR with your dev branch, it gives a bunch of other commits to include in my PR. I don't see a way to exclude those and only allow mine in it. 
screen shot 2016-08-24 at 11 18 57 am
I don't have access to your project, so can't update files directly right?

**Comment by dr-dimitru** [comment]
It's totally fine, send it

**Pull request closed without merging**
