### PR TITLE
added dynamicStoragePath 

### PR DESCRIPTION
**Pull request by salmanhasni**
The PR is against this issue https://github.com/VeliovGroup/Meteor-Files/issues/225

### CODE REVIEW

**Comment by salmanhasni** [comment]
@dr-dimitru please have a look, I have did smoke over it.
does it looks good to you ? if yes then I can further proceed for documentation changes for this PR.

**Comment by salmanhasni** [comment]
**Usage Example**

```
this.Images = new Meteor.Files({
    debug: true,
    collectionName: 'Images',
    allowClientCode: false, // Disallow remove files from Client
    storagePath: "/home/salman/Images",
    onBeforeUpload: function (file) {
        if (file.size <= 1024*1024*10 && /png|jpg|jpeg/i.test(file.extension)) {
        return true;
        } else {
        return 'Please upload image, with size equal or less than 10MB';
        }
    },
    switchStorage: function() {
         /*Computation here for dynamic path*/
        var dynamicDirectoryPath = "/home/salman/Pictures";
        return dynamicDirectoryPath;
    }
});
```

**Comment by dr-dimitru** [comment]
I prefer to make `storagePath` as *Function*, without adding new properties to class.
For backward compatibility, if `storagePath` is *String* we just wrap it to function.

**Comment by dr-dimitru** [comment]
And it should be dynamic for every upload, with passed metadata into it.

**Comment by salmanhasni** [comment]
@dr-dimitru your solutions seems to be more feasible (Y)

**Pull request closed without merging**
