### PR TITLE
Update gridfs-streaming.md

### PR DESCRIPTION
**Pull request by Prinzhorn**
Correct me if I'm wrong, but this is not accurate. The files are streamed to the client using `bucket.openDownloadStream`, see https://github.com/veliovgroup/Meteor-Files/blob/master/docs/gridfs-bucket-integration.md#4-create-download-handler

That means the entire file does _not_ need to be held in server memory. Correct?

### CODE REVIEW

**Comment by jankapunkt** [comment]
Why do you create a PR for each of these? I mean it's okay to have distinctive PRs but this is all about the gridfs documentation. I think this could all be handled in one PR having several commits for each changes. Makes reviewing also much easier.

cc @dr-dimitru

**Comment by Prinzhorn** [comment]
Because I'm following along the docs and open a PR when I run into an issue (using the GitHub UI). That is much easier on my end than to first keep a list of them and the go back to create a single PR and edit my fork and then push the changes. I though it would be a lot easier for you to hit merge five time than for me to 


Also I wasn't expecting to run into that many issues when I started and thought it would would remain a single PR.

**Comment by jankapunkt** [comment]
> I though it would be a lot easier for you to hit merge five times than for me to keep updating a PR

That's not how a review works :-) So I have to make 5 reviews now and in the end one more final review to see if all the changed code examples work, when applying to a real app, for example like this one: https://github.com/veliovgroup/files-gridfs-autoform-example

**Comment by jankapunkt** [comment]
@Prinzhorn let me see if I can merge them into one, git is fortunately not limited to what GitHub offers

**Comment by Prinzhorn** [comment]
Thanks!

Two of them are just text, nothing to test. One is literally syntax error (semicolon in an object literal). The two forgotten `export ` make copy paste harder. And `createAfterUpdate` is a typo because the code that uses it has `onAfterUpload: createOnAfterUpload(imageBucket),`.

**Comment by jankapunkt** [comment]
I will add code for gird-fs straming with GridFSBucket, since it is slightly different. However I first need to make this running in our project at work.

**Review by dr-dimitru — APPROVED** [review]

**Pull request merged**
