### PR TITLE
be able to pass userId to addFile (API)

### PR DESCRIPTION
**Pull request by menelike**
solves #298

Do we need to to set userId to null? Isn't it better to skip that (userId === undefined)?

*no expert in CoffeeScript, review advised*

### CODE REVIEW

**Comment by dr-dimitru** [comment]
@menelike the logic behind current implementation is simple - __always__ return `null` if there is no user

Well, if we are going to let set an `userId` here, should we add same ability to other methods, for consistency?

**Comment by menelike** [comment]
@dr-dimitru sorry I missed that one, hope it worked out fine

**Comment by dr-dimitru** [comment]
Yes, already pushed to dev

**Comment by dr-dimitru** [comment]
Published in [v1.7.6](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.6)

**Pull request merged**
