### PR TITLE
updated the s3 example to use aws-sdk - supported

### PR DESCRIPTION
**Pull request by vtocco**
I have updated the docs and removed knox and used the supported aws-sdk. Also have included some other security solutions to protected files.

### CODE REVIEW

**Comment by paulincai** [comment]
Hi @vtocco  and @dr-dimitru would you please be so kind and detail a bit how do you actually get a file from S3 securely into an  tag. I noticed there is a method, e.g.

 _if "myImages" is my collection_, myImages.files.findOne({})**.link(version)** which is invalid, at least when I try to use it in the context of S3. I consider a business app (React) where only I should see my own graphic assets. Thanks a lot.

**Comment by dr-dimitru** [comment]
@paulincai better to ask at #307 , there is a lots of folks who is dealing with AWS daily

**Comment by dr-dimitru** [comment]
@vtocco thank you a lot! And pardon me for delay

**Comment by dr-dimitru** [comment]
@vtocco I've edited your suggestions and removed all unrelated to AWS:S3 code.
Although I've removed it, it doesn't mean it isn't useful.
I'll be happy to accept one or more PRs to appropriate sections of the docs.

**Comment by dr-dimitru** [comment]
Hello @vtocco ,

Unfortunately this is not working for AWS:S3 + Heroku.
Idk why it works on locally on dev machine, and on dedicated server, but not Heroku, wasted 5 hours trying to figure this out.

Here is my attempts:
 - https://github.com/VeliovGroup/Meteor-Files/commit/2e14035a62836231b6b15d9003e0932578e6957b
 - https://github.com/VeliovGroup/Meteor-Files/commit/3a70c0717e3e34ca94bfadee0b4a3de39d888a89

If you have any ideas - I'll be appreciated.
Current "broken" behavior can be found at https://files.veliov.com , try to upload video or audio file larger than 10MB and play it...

Thank you.

**Comment by dr-dimitru** [comment]
Btw "broken" requests ended up with:
```
code=H27 desc="Client Request Interrupted"
```
On Heroku end, there is no explanation for it, as `H27` should only be thrown if user interrupted request, like with closing a browser.... hope that helps

**Comment by paulincai** [comment]
@dr-dimitru I know exactly how 5 hour look like on the exact same problem :). I am getting 
__
_May 18 21:40:31 app heroku/router:  sock=backend at=error c**ode=H18 desc="Server Request Interrupted"** method=GET path="/cdn/storage/cameraFiles/xxxxxxxxxx.jpeg" host=app.herokuapp.com request_id=afbff1f2-1345-4740-bfae-93ecf4087011 fwd="xx.xx.xx.xx" dyno=web.1 connect=0ms service=325ms **status=503 bytes= protocol=https**  
I am having like 8 small images of about 14kb each._

**Comment by vtocco** [comment]
I don't have any experience with Heroku, the aws client is almost the same as knox so the behavior should be the same. I am heading out of town for a couple weeks, can spin up an instance and look when I get back.

**Comment by dr-dimitru** [comment]
@vtocco @paulincai this was finally fixed
 1. Heroku error was caused by my reverse-proxy setup. Nginx strips Range header, and when browser receives unexpected response it restarts connection
 2. AWS:S3 official lib has some weird behavior, [see how it was fixed](https://github.com/VeliovGroup/Meteor-Files/commit/5cb154536c21994192fe84522117307398f05950)

Thank you guys once more.

**Pull request merged**
