### PR TITLE
GridFS example

### PR DESCRIPTION
**Pull request by epaminond**

### CODE REVIEW

**Comment by Neobii** [comment]
I tested this code and it uploads to GridFS on my side, thanks @epaminond !

**Comment by dr-dimitru** [comment]
@Neobii thank you
@epaminond will you use `onAfterRemove` in this example?

**Comment by epaminond** [comment]
@dr-dimitru, yes, I'll test it and update an example.

**Comment by dr-dimitru** [comment]
@epaminond Thank you, looks great to me.
I'll merge today and publish v1.6.0 (*finally*)

**Pull request merged**
