### PR TITLE
fix: send meta Object with first chunk  dev

### PR DESCRIPTION
**Pull request by menelike**
This solves https://github.com/VeliovGroup/Meteor-Files/issues/79

Reverted https://github.com/VeliovGroup/Meteor-Files/issues/79#issuecomment-220431951 because
https://github.com/VeliovGroup/Meteor-Files/issues/79#issuecomment-220531902 is the better approach.

This transmit the `chunkId` (to be able to determine if meta should have been set or not (Server)) and the `meta` object as well as part of each `onBeforeUpload` call. Both are accessible as context e.g. `this`.

### CODE REVIEW

**Comment by dr-dimitru** [comment]
Hey @menelike 
1. We shouldn't revert the a265fcf as it's fixes incompatibility of `onBeforeUpload` between Server and Client
2. So you think we should allow sending `meta` with every chunk? What if there is will be big amount of data?

**Comment by menelike** [comment]
Based on

```
const FooFiles = new FilesCollection({
  collectionName: 'FooFiles',
  allowClientCode: false, // Disallow remove files from Client
  onBeforeUpload: function onBeforeUpload(fileRef) {
    console.log('fileRef output:');
    console.log(fileRef);
    console.log('context:');
    console.log(this);
    return true;
     },
});
```

if you upload one file with a few chunks, these are the logs:

Server Log based on https://github.com/VeliovGroup/Meteor-Files/pull/80/commits/0b9f1b14e63ab7e480c5c61f058781dbaf386416 (this PR)

```
I20160521-21:27:33.740(2)? fileRef output:
I20160521-21:27:33.770(2)? { size: 1377589,
I20160521-21:27:33.771(2)?   type: 'application/zip',
I20160521-21:27:33.771(2)?   name: 'Foo.zip',
I20160521-21:27:33.772(2)?   ext: 'zip',
I20160521-21:27:33.772(2)?   extension: 'zip',
I20160521-21:27:33.773(2)?   extensionWithDot: '.zip',
I20160521-21:27:33.773(2)?   mime: 'application/zip',
I20160521-21:27:33.773(2)?   'mime-type': 'application/zip' }
I20160521-21:27:33.774(2)? context:
I20160521-21:27:33.774(2)? { file: 
I20160521-21:27:33.775(2)?    { size: 1377589,
I20160521-21:27:33.775(2)?      type: 'application/zip',
I20160521-21:27:33.775(2)?      name: 'Foo.zip',
I20160521-21:27:33.775(2)?      ext: 'zip',
I20160521-21:27:33.776(2)?      extension: 'zip',
I20160521-21:27:33.803(2)?      extensionWithDot: '.zip',
I20160521-21:27:33.803(2)?      mime: 'application/zip',
I20160521-21:27:33.804(2)?      'mime-type': 'application/zip' },
I20160521-21:27:33.804(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:27:33.804(2)?   user: [Function],
I20160521-21:27:33.804(2)?   meta: null,
I20160521-21:27:33.805(2)?   chunkId: 5 }
I20160521-21:27:33.891(2)? fileRef output:
I20160521-21:27:33.891(2)? { size: 1377589,
I20160521-21:27:33.891(2)?   type: 'application/zip',
I20160521-21:27:33.891(2)?   name: 'Foo.zip',
I20160521-21:27:33.892(2)?   ext: 'zip',
I20160521-21:27:33.892(2)?   extension: 'zip',
I20160521-21:27:33.892(2)?   extensionWithDot: '.zip',
I20160521-21:27:33.892(2)?   mime: 'application/zip',
I20160521-21:27:33.893(2)?   'mime-type': 'application/zip' }
I20160521-21:27:33.893(2)? context:
I20160521-21:27:33.898(2)? { file: 
I20160521-21:27:33.898(2)?    { size: 1377589,
I20160521-21:27:33.898(2)?      type: 'application/zip',
I20160521-21:27:33.898(2)?      name: 'Foo.zip',
I20160521-21:27:33.898(2)?      ext: 'zip',
I20160521-21:27:33.899(2)?      extension: 'zip',
I20160521-21:27:33.899(2)?      extensionWithDot: '.zip',
I20160521-21:27:33.899(2)?      mime: 'application/zip',
I20160521-21:27:33.899(2)?      'mime-type': 'application/zip' },
I20160521-21:27:33.899(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:27:33.899(2)?   user: [Function],
I20160521-21:27:33.901(2)?   meta: { fooId: 'pB9fYnRKkhuBEeCP8', username: 'foo' },
I20160521-21:27:33.901(2)?   chunkId: 1 }
I20160521-21:27:34.019(2)? fileRef output:
I20160521-21:27:34.019(2)? { size: 1377589,
I20160521-21:27:34.019(2)?   type: 'application/zip',
I20160521-21:27:34.019(2)?   name: 'Foo.zip',
I20160521-21:27:34.020(2)?   ext: 'zip',
I20160521-21:27:34.020(2)?   extension: 'zip',
I20160521-21:27:34.020(2)?   extensionWithDot: '.zip',
I20160521-21:27:34.020(2)?   mime: 'application/zip',
I20160521-21:27:34.020(2)?   'mime-type': 'application/zip' }
I20160521-21:27:34.036(2)? context:
I20160521-21:27:34.038(2)? { file: 
I20160521-21:27:34.038(2)?    { size: 1377589,
I20160521-21:27:34.038(2)?      type: 'application/zip',
I20160521-21:27:34.039(2)?      name: 'Foo.zip',
I20160521-21:27:34.039(2)?      ext: 'zip',
I20160521-21:27:34.039(2)?      extension: 'zip',
I20160521-21:27:34.039(2)?      extensionWithDot: '.zip',
I20160521-21:27:34.039(2)?      mime: 'application/zip',
I20160521-21:27:34.039(2)?      'mime-type': 'application/zip' },
I20160521-21:27:34.039(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:27:34.039(2)?   user: [Function],
I20160521-21:27:34.040(2)?   meta: null,
I20160521-21:27:34.040(2)?   chunkId: 2 }
I20160521-21:27:34.075(2)? fileRef output:
I20160521-21:27:34.075(2)? { size: 1377589,
I20160521-21:27:34.076(2)?   type: 'application/zip',
I20160521-21:27:34.076(2)?   name: 'Foo.zip',
I20160521-21:27:34.076(2)?   ext: 'zip',
I20160521-21:27:34.076(2)?   extension: 'zip',
I20160521-21:27:34.076(2)?   extensionWithDot: '.zip',
I20160521-21:27:34.077(2)?   mime: 'application/zip',
I20160521-21:27:34.077(2)?   'mime-type': 'application/zip' }
I20160521-21:27:34.077(2)? context:
I20160521-21:27:34.081(2)? { file: 
I20160521-21:27:34.081(2)?    { size: 1377589,
I20160521-21:27:34.081(2)?      type: 'application/zip',
I20160521-21:27:34.082(2)?      name: 'Foo.zip',
I20160521-21:27:34.082(2)?      ext: 'zip',
I20160521-21:27:34.082(2)?      extension: 'zip',
I20160521-21:27:34.082(2)?      extensionWithDot: '.zip',
I20160521-21:27:34.082(2)?      mime: 'application/zip',
I20160521-21:27:34.082(2)?      'mime-type': 'application/zip' },
I20160521-21:27:34.083(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:27:34.083(2)?   user: [Function],
I20160521-21:27:34.083(2)?   meta: null,
I20160521-21:27:34.083(2)?   chunkId: 3 }
I20160521-21:27:34.185(2)? fileRef output:
I20160521-21:27:34.187(2)? { size: 1377589,
I20160521-21:27:34.187(2)?   type: 'application/zip',
I20160521-21:27:34.187(2)?   name: 'Foo.zip',
I20160521-21:27:34.187(2)?   ext: 'zip',
I20160521-21:27:34.187(2)?   extension: 'zip',
I20160521-21:27:34.187(2)?   extensionWithDot: '.zip',
I20160521-21:27:34.187(2)?   mime: 'application/zip',
I20160521-21:27:34.188(2)?   'mime-type': 'application/zip' }
I20160521-21:27:34.188(2)? context:
I20160521-21:27:34.188(2)? { file: 
I20160521-21:27:34.188(2)?    { size: 1377589,
I20160521-21:27:34.188(2)?      type: 'application/zip',
I20160521-21:27:34.188(2)?      name: 'Foo.zip',
I20160521-21:27:34.188(2)?      ext: 'zip',
I20160521-21:27:34.189(2)?      extension: 'zip',
I20160521-21:27:34.189(2)?      extensionWithDot: '.zip',
I20160521-21:27:34.189(2)?      mime: 'application/zip',
I20160521-21:27:34.189(2)?      'mime-type': 'application/zip' },
I20160521-21:27:34.189(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:27:34.189(2)?   user: [Function],
I20160521-21:27:34.189(2)?   meta: null,
I20160521-21:27:34.189(2)?   chunkId: 4 }
I20160521-21:27:34.208(2)? fileRef output:
I20160521-21:27:34.209(2)? { size: 1377589,
I20160521-21:27:34.209(2)?   type: 'application/zip',
I20160521-21:27:34.209(2)?   name: 'Foo.zip',
I20160521-21:27:34.209(2)?   ext: 'zip',
I20160521-21:27:34.209(2)?   extension: 'zip',
I20160521-21:27:34.209(2)?   extensionWithDot: '.zip',
I20160521-21:27:34.210(2)?   mime: 'application/zip',
I20160521-21:27:34.210(2)?   'mime-type': 'application/zip' }
I20160521-21:27:34.221(2)? context:
I20160521-21:27:34.221(2)? { file: 
I20160521-21:27:34.221(2)?    { size: 1377589,
I20160521-21:27:34.221(2)?      type: 'application/zip',
I20160521-21:27:34.222(2)?      name: 'Foo.zip',
I20160521-21:27:34.222(2)?      ext: 'zip',
I20160521-21:27:34.222(2)?      extension: 'zip',
I20160521-21:27:34.223(2)?      extensionWithDot: '.zip',
I20160521-21:27:34.223(2)?      mime: 'application/zip',
I20160521-21:27:34.223(2)?      'mime-type': 'application/zip' },
I20160521-21:27:34.223(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:27:34.223(2)?   user: [Function],
I20160521-21:27:34.223(2)?   meta: { fooId: 'pB9fYnRKkhuBEeCP8', username: 'foo' },
I20160521-21:27:34.223(2)?   chunkId: -1 }
```

You can see `meta` is transmitted only 2 times, on `chunkId` 1 (first data packet) and -1 (EOF or default).
And we can access the `chunkId` and determine if we should do further validations based on `meta.fooId`

This is the log based on https://github.com/VeliovGroup/Meteor-Files/commit/5e77d6ac202d219544a03b93457835d66f64fcc4

```
I20160521-21:36:22.533(2)? fileRef output:
I20160521-21:36:22.537(2)? { name: 'Foo.zip',
I20160521-21:36:22.537(2)?   extension: 'zip',
I20160521-21:36:22.537(2)?   path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.537(2)?   meta: {},
I20160521-21:36:22.538(2)?   type: 'application/zip',
I20160521-21:36:22.538(2)?   size: 1377589,
I20160521-21:36:22.541(2)?   versions: 
I20160521-21:36:22.541(2)?    { original: 
I20160521-21:36:22.542(2)?       { path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.542(2)?         size: 1377589,
I20160521-21:36:22.542(2)?         type: 'application/zip',
I20160521-21:36:22.542(2)?         extension: 'zip' } },
I20160521-21:36:22.543(2)?   isVideo: false,
I20160521-21:36:22.543(2)?   isAudio: false,
I20160521-21:36:22.543(2)?   isImage: false,
I20160521-21:36:22.543(2)?   isText: false,
I20160521-21:36:22.543(2)?   isJSON: false,
I20160521-21:36:22.544(2)?   _prefix: '0dcd4313d1d69716d073070e28230beb5fbaa875a08b2d4436844bed5283d3f2',
I20160521-21:36:22.544(2)?   _storagePath: 'assets/app/uploads/FooFiles',
I20160521-21:36:22.544(2)?   _downloadRoute: '/cdn/storage',
I20160521-21:36:22.544(2)?   _collectionName: 'FooFiles',
I20160521-21:36:22.544(2)?   _id: 'TuiiG44SFDyGdn9ND',
I20160521-21:36:22.545(2)?   userId: 'kSc4u7h5a3fjcfukw' }
I20160521-21:36:22.545(2)? context:
I20160521-21:36:22.545(2)? { file: 
I20160521-21:36:22.545(2)?    { size: 1377589,
I20160521-21:36:22.546(2)?      type: 'application/zip',
I20160521-21:36:22.546(2)?      name: 'Foo.zip',
I20160521-21:36:22.546(2)?      meta: {},
I20160521-21:36:22.546(2)?      ext: 'zip',
I20160521-21:36:22.546(2)?      extension: 'zip',
I20160521-21:36:22.547(2)?      extensionWithDot: '.zip',
I20160521-21:36:22.550(2)?      mime: 'application/zip',
I20160521-21:36:22.550(2)?      'mime-type': 'application/zip',
I20160521-21:36:22.550(2)?      path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip' },
I20160521-21:36:22.551(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:36:22.551(2)?   user: [Function] }
I20160521-21:36:22.618(2)? fileRef output:
I20160521-21:36:22.619(2)? { name: 'Foo.zip',
I20160521-21:36:22.619(2)?   extension: 'zip',
I20160521-21:36:22.620(2)?   path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.620(2)?   meta: { fooId: 'pB9fYnRKkhuBEeCP8', username: 'foo' },
I20160521-21:36:22.620(2)?   type: 'application/zip',
I20160521-21:36:22.620(2)?   size: 1377589,
I20160521-21:36:22.620(2)?   versions: 
I20160521-21:36:22.620(2)?    { original: 
I20160521-21:36:22.620(2)?       { path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.620(2)?         size: 1377589,
I20160521-21:36:22.620(2)?         type: 'application/zip',
I20160521-21:36:22.621(2)?         extension: 'zip' } },
I20160521-21:36:22.621(2)?   isVideo: false,
I20160521-21:36:22.621(2)?   isAudio: false,
I20160521-21:36:22.621(2)?   isImage: false,
I20160521-21:36:22.621(2)?   isText: false,
I20160521-21:36:22.621(2)?   isJSON: false,
I20160521-21:36:22.621(2)?   _prefix: '0dcd4313d1d69716d073070e28230beb5fbaa875a08b2d4436844bed5283d3f2',
I20160521-21:36:22.622(2)?   _storagePath: 'assets/app/uploads/FooFiles',
I20160521-21:36:22.622(2)?   _downloadRoute: '/cdn/storage',
I20160521-21:36:22.622(2)?   _collectionName: 'FooFiles',
I20160521-21:36:22.622(2)?   _id: 'TuiiG44SFDyGdn9ND',
I20160521-21:36:22.622(2)?   userId: 'kSc4u7h5a3fjcfukw' }
I20160521-21:36:22.622(2)? context:
I20160521-21:36:22.623(2)? { file: 
I20160521-21:36:22.627(2)?    { size: 1377589,
I20160521-21:36:22.627(2)?      type: 'application/zip',
I20160521-21:36:22.627(2)?      name: 'Foo.zip',
I20160521-21:36:22.627(2)?      meta: { fooId: 'pB9fYnRKkhuBEeCP8', username: 'foo' },
I20160521-21:36:22.628(2)?      ext: 'zip',
I20160521-21:36:22.628(2)?      extension: 'zip',
I20160521-21:36:22.628(2)?      extensionWithDot: '.zip',
I20160521-21:36:22.628(2)?      mime: 'application/zip',
I20160521-21:36:22.628(2)?      'mime-type': 'application/zip',
I20160521-21:36:22.628(2)?      path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip' },
I20160521-21:36:22.628(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:36:22.628(2)?   user: [Function] }
I20160521-21:36:22.675(2)? fileRef output:
I20160521-21:36:22.676(2)? { name: 'Foo.zip',
I20160521-21:36:22.676(2)?   extension: 'zip',
I20160521-21:36:22.676(2)?   path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.676(2)?   meta: {},
I20160521-21:36:22.676(2)?   type: 'application/zip',
I20160521-21:36:22.677(2)?   size: 1377589,
I20160521-21:36:22.677(2)?   versions: 
I20160521-21:36:22.677(2)?    { original: 
I20160521-21:36:22.677(2)?       { path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.677(2)?         size: 1377589,
I20160521-21:36:22.677(2)?         type: 'application/zip',
I20160521-21:36:22.677(2)?         extension: 'zip' } },
I20160521-21:36:22.677(2)?   isVideo: false,
I20160521-21:36:22.677(2)?   isAudio: false,
I20160521-21:36:22.677(2)?   isImage: false,
I20160521-21:36:22.677(2)?   isText: false,
I20160521-21:36:22.678(2)?   isJSON: false,
I20160521-21:36:22.678(2)?   _prefix: '0dcd4313d1d69716d073070e28230beb5fbaa875a08b2d4436844bed5283d3f2',
I20160521-21:36:22.678(2)?   _storagePath: 'assets/app/uploads/FooFiles',
I20160521-21:36:22.678(2)?   _downloadRoute: '/cdn/storage',
I20160521-21:36:22.678(2)?   _collectionName: 'FooFiles',
I20160521-21:36:22.678(2)?   _id: 'TuiiG44SFDyGdn9ND',
I20160521-21:36:22.678(2)?   userId: 'kSc4u7h5a3fjcfukw' }
I20160521-21:36:22.678(2)? context:
I20160521-21:36:22.678(2)? { file: 
I20160521-21:36:22.678(2)?    { size: 1377589,
I20160521-21:36:22.679(2)?      type: 'application/zip',
I20160521-21:36:22.679(2)?      name: 'Foo.zip',
I20160521-21:36:22.679(2)?      meta: {},
I20160521-21:36:22.680(2)?      ext: 'zip',
I20160521-21:36:22.680(2)?      extension: 'zip',
I20160521-21:36:22.680(2)?      extensionWithDot: '.zip',
I20160521-21:36:22.680(2)?      mime: 'application/zip',
I20160521-21:36:22.681(2)?      'mime-type': 'application/zip',
I20160521-21:36:22.681(2)?      path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip' },
I20160521-21:36:22.681(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:36:22.681(2)?   user: [Function] }
I20160521-21:36:22.711(2)? fileRef output:
I20160521-21:36:22.712(2)? { name: 'Foo.zip',
I20160521-21:36:22.712(2)?   extension: 'zip',
I20160521-21:36:22.713(2)?   path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.713(2)?   meta: {},
I20160521-21:36:22.713(2)?   type: 'application/zip',
I20160521-21:36:22.713(2)?   size: 1377589,
I20160521-21:36:22.713(2)?   versions: 
I20160521-21:36:22.713(2)?    { original: 
I20160521-21:36:22.713(2)?       { path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.713(2)?         size: 1377589,
I20160521-21:36:22.713(2)?         type: 'application/zip',
I20160521-21:36:22.713(2)?         extension: 'zip' } },
I20160521-21:36:22.713(2)?   isVideo: false,
I20160521-21:36:22.714(2)?   isAudio: false,
I20160521-21:36:22.714(2)?   isImage: false,
I20160521-21:36:22.714(2)?   isText: false,
I20160521-21:36:22.714(2)?   isJSON: false,
I20160521-21:36:22.714(2)?   _prefix: '0dcd4313d1d69716d073070e28230beb5fbaa875a08b2d4436844bed5283d3f2',
I20160521-21:36:22.714(2)?   _storagePath: 'assets/app/uploads/FooFiles',
I20160521-21:36:22.714(2)?   _downloadRoute: '/cdn/storage',
I20160521-21:36:22.714(2)?   _collectionName: 'FooFiles',
I20160521-21:36:22.715(2)?   userId: 'kSc4u7h5a3fjcfukw' }
I20160521-21:36:22.714(2)?   _id: 'TuiiG44SFDyGdn9ND',
I20160521-21:36:22.715(2)? context:
I20160521-21:36:22.715(2)? { file: 
I20160521-21:36:22.716(2)?    { size: 1377589,
I20160521-21:36:22.716(2)?      type: 'application/zip',
I20160521-21:36:22.716(2)?      name: 'Foo.zip',
I20160521-21:36:22.719(2)?      meta: {},
I20160521-21:36:22.719(2)?      ext: 'zip',
I20160521-21:36:22.719(2)?      extension: 'zip',
I20160521-21:36:22.719(2)?      extensionWithDot: '.zip',
I20160521-21:36:22.719(2)?      mime: 'application/zip',
I20160521-21:36:22.720(2)?      'mime-type': 'application/zip',
I20160521-21:36:22.720(2)?      path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip' },
I20160521-21:36:22.720(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:36:22.720(2)?   user: [Function] }
I20160521-21:36:22.772(2)? fileRef output:
I20160521-21:36:22.774(2)? { name: 'Foo.zip',
I20160521-21:36:22.774(2)?   extension: 'zip',
I20160521-21:36:22.775(2)?   path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.775(2)?   meta: {},
I20160521-21:36:22.775(2)?   type: 'application/zip',
I20160521-21:36:22.775(2)?   size: 1377589,
I20160521-21:36:22.775(2)?   versions: 
I20160521-21:36:22.775(2)?    { original: 
I20160521-21:36:22.775(2)?       { path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.775(2)?         size: 1377589,
I20160521-21:36:22.775(2)?         type: 'application/zip',
I20160521-21:36:22.775(2)?         extension: 'zip' } },
I20160521-21:36:22.776(2)?   isVideo: false,
I20160521-21:36:22.776(2)?   isAudio: false,
I20160521-21:36:22.776(2)?   isImage: false,
I20160521-21:36:22.776(2)?   isText: false,
I20160521-21:36:22.776(2)?   isJSON: false,
I20160521-21:36:22.776(2)?   _prefix: '0dcd4313d1d69716d073070e28230beb5fbaa875a08b2d4436844bed5283d3f2',
I20160521-21:36:22.776(2)?   _storagePath: 'assets/app/uploads/FooFiles',
I20160521-21:36:22.776(2)?   _downloadRoute: '/cdn/storage',
I20160521-21:36:22.776(2)?   _collectionName: 'FooFiles',
I20160521-21:36:22.777(2)?   _id: 'TuiiG44SFDyGdn9ND',
I20160521-21:36:22.777(2)?   userId: 'kSc4u7h5a3fjcfukw' }
I20160521-21:36:22.777(2)? context:
I20160521-21:36:22.777(2)? { file: 
I20160521-21:36:22.777(2)?    { size: 1377589,
I20160521-21:36:22.777(2)?      type: 'application/zip',
I20160521-21:36:22.777(2)?      name: 'Foo.zip',
I20160521-21:36:22.778(2)?      meta: {},
I20160521-21:36:22.778(2)?      ext: 'zip',
I20160521-21:36:22.778(2)?      extension: 'zip',
I20160521-21:36:22.779(2)?      extensionWithDot: '.zip',
I20160521-21:36:22.779(2)?      mime: 'application/zip',
I20160521-21:36:22.779(2)?      'mime-type': 'application/zip',
I20160521-21:36:22.779(2)?      path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip' },
I20160521-21:36:22.779(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:36:22.780(2)?   user: [Function] }
I20160521-21:36:22.808(2)? fileRef output:
I20160521-21:36:22.809(2)? { name: 'Foo.zip',
I20160521-21:36:22.809(2)?   extension: 'zip',
I20160521-21:36:22.809(2)?   path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.809(2)?   meta: { fooId: 'pB9fYnRKkhuBEeCP8', username: 'foo' },
I20160521-21:36:22.810(2)?   type: 'application/zip',
I20160521-21:36:22.810(2)?   size: 1377589,
I20160521-21:36:22.810(2)?   versions: 
I20160521-21:36:22.810(2)?    { original: 
I20160521-21:36:22.810(2)?       { path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip',
I20160521-21:36:22.810(2)?         size: 1377589,
I20160521-21:36:22.811(2)?         type: 'application/zip',
I20160521-21:36:22.811(2)?         extension: 'zip' } },
I20160521-21:36:22.811(2)?   isVideo: false,
I20160521-21:36:22.811(2)?   isAudio: false,
I20160521-21:36:22.811(2)?   isImage: false,
I20160521-21:36:22.811(2)?   isText: false,
I20160521-21:36:22.811(2)?   isJSON: false,
I20160521-21:36:22.812(2)?   _prefix: '0dcd4313d1d69716d073070e28230beb5fbaa875a08b2d4436844bed5283d3f2',
I20160521-21:36:22.812(2)?   _storagePath: 'assets/app/uploads/FooFiles',
I20160521-21:36:22.812(2)?   _downloadRoute: '/cdn/storage',
I20160521-21:36:22.812(2)?   _collectionName: 'FooFiles',
I20160521-21:36:22.812(2)?   _id: 'TuiiG44SFDyGdn9ND',
I20160521-21:36:22.812(2)?   userId: 'kSc4u7h5a3fjcfukw' }
I20160521-21:36:22.812(2)? context:
I20160521-21:36:22.813(2)? { file: 
I20160521-21:36:22.813(2)?    { size: 1377589,
I20160521-21:36:22.813(2)?      type: 'application/zip',
I20160521-21:36:22.813(2)?      name: 'Foo.zip',
I20160521-21:36:22.814(2)?      meta: { fooId: 'pB9fYnRKkhuBEeCP8', username: 'foo' },
I20160521-21:36:22.814(2)?      ext: 'zip',
I20160521-21:36:22.814(2)?      extension: 'zip',
I20160521-21:36:22.814(2)?      extensionWithDot: '.zip',
I20160521-21:36:22.814(2)?      mime: 'application/zip',
I20160521-21:36:22.815(2)?      'mime-type': 'application/zip',
I20160521-21:36:22.815(2)?      path: 'assets/app/uploads/FooFiles/TuiiG44SFDyGdn9ND.zip' },
I20160521-21:36:22.815(2)?   userId: 'kSc4u7h5a3fjcfukw',
I20160521-21:36:22.821(2)?   user: [Function] }
````

Meta is transmitted 2 times like before, but we skip all this internal data as an additional huge overhead. 
Even if this is needed, it should only be sent when meta data is sent as well. 

I'm not sure if this was intended at all, you don't want to add metadata on each chunk (valid point regarding performance, approved), but then you add a ton of internal data which breaks your argument about performance. This is why I reverted the commit.

**Comment by dr-dimitru** [comment]
> In case this behavior is intended, I sure can add a patch which adds this data, but I advise to only add it when meta data is added too

Agree, but this needs to be done on top of a265fcf. And it's complex right now, as we may receive first chunk which not actually the first one, and if there is no data like: file-type and extension, it will involve `.lock` files, which should be properly renamed after last chunk is received.

**Comment by menelike** [comment]
@dr-dimitru 
You are right, this PR is nonsense, it always transmits meta data. I completely misunderstood the data flow. 
I hope that https://github.com/VeliovGroup/Meteor-Files/pull/82 fits as a replacement.

**Pull request closed without merging**
